from pathlib import Path
import ast,json,math,shutil,hashlib
import pandas as pd
ROOT=Path(__file__).resolve().parents[2]; OUT=Path(__file__).resolve().parent; SKILL=ROOT/'.codex/skills/lieflat-charts'
source=ROOT/'charts/hdb/transactions.csv';d=pd.read_csv(source);d['year']=d.month.str[:4].astype(int);d['lease']=d.remaining_lease.str.extract(r'(\d+) years')[0].astype(int)+d.remaining_lease.str.extract(r'(\d+) months')[0].fillna(0).astype(int)/12;d['psm']=d.resale_price/d.floor_area_sqm
assert len(d)==242259 and (d.floor_area_sqm>0).all()
y=d[d.year==2025];DATA=json.loads((ROOT/'charts/hdb/chart-data.json').read_text());bands=DATA['bands'];d['band']=pd.cut(d.lease,[0,50,60,70,80,100],right=False,labels=bands);y=d[d.year==2025]
DATA['monthly']=[dict(name=m,v=float(g.psm.median()),n=len(g)) for m,g in y.groupby('month')]
towns=list(y.town.value_counts().index[:20]);DATA['towns']=[dict(name=t.title(),lease=float(y[y.town==t].lease.median()),psm=float(y[y.town==t].psm.median()),n=int((y.town==t).sum())) for t in towns]
gaps=[]
for t,g in y.groupby('town'):
 a=g[g.lease<60];b=g[g.lease>=80]
 if len(a)>=30 and len(b)>=30:gaps.append(dict(name=t.title(),v=float((a.psm.median()/b.psm.median()-1)*100),a=float(a.psm.median()),b=float(b.psm.median()),na=len(a),nb=len(b),n=len(g)))
DATA['gaps']=sorted(gaps,key=lambda a:-a['n'])[:6];chosen=[a['name'].upper() for a in DATA['gaps']];DATA['matrix_towns']=[t.title() for t in chosen];DATA['town_matrix']=[dict(town=t.title(),band=str(b),v=float(g.psm.median()),n=len(g)) for (t,b),g in y[y.town.isin(chosen)].groupby(['town','band'],observed=True)]
million=y[y.resale_price>=1000000];DATA['million']=dict(n=len(million),total=len(y),pct=len(million)/len(y)*100,short_n=int((million.lease<60).sum()),min_lease=float(million.lease.min()))
(OUT/'data.json').write_text(json.dumps(DATA,indent=2));shutil.copyfile(source,OUT/'transactions.csv')
# Reuse the already adapted real-gallery F5/F6/L9 rendering blocks.
tree=ast.parse((ROOT/'charts/hdb/build_charts.py').read_text());base=next(ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='render' for t in n.targets))
tokens=(SKILL/'mono-tokens.js').read_text().replace('</script>','<\\/script>')
new=r'''
// L3 Barcode Lollipop: full-height period hairlines, capped stems, lollipop marks.
function barcode(s){const D=DATA.monthly,max=9000,min=0,base=270,map=v=>base-v/max*220,x=i=>95+i*62;for(let i=0;i<D.length;i++)el(s,'line',{x1:x(i),x2:x(i),y1:30,y2:base,stroke:GRID,'stroke-width':.7,class:'fade'});[0,3000,6000,9000].forEach(v=>label(s,65,map(v)+3,money(v),{'text-anchor':'end','font-size':9}));D.forEach((a,i)=>{const yy=map(a.v);el(s,'line',{x1:x(i),x2:x(i),y1:yy,y2:Math.min(base,yy+30),stroke:INK,'stroke-width':1.1,class:'fade',style:`animation-delay:${i*.04}s`});const c=el(s,'circle',{cx:x(i),cy:yy,r:3.3,fill:INK,class:'pop',style:`animation-delay:${i*.04}s`});tip(c,`${a.name}: ${money(a.v)}/m² median; n=${a.n}`);label(s,x(i),yy-12,money(a.v),{'font-size':9,'font-weight':800,'text-anchor':'middle'});label(s,x(i),292,a.name.slice(5),{'text-anchor':'middle'})});label(s,70,330,'Registration month in 2025 · price per square metre · one mark = monthly median',{fill:L[2]})}
// L4 Arc Matrix: categorical arc rows and area-proportional circles.
function arcs(s){const T=DATA.matrix_towns,B=DATA.bands,max=Math.max(...DATA.town_matrix.map(a=>a.v)),row=i=>75+i*45,col=j=>245+j*120,dy=j=>-12*Math.sin(Math.PI*j/4);B.forEach((b,j)=>label(s,col(j),30,b,{'text-anchor':'middle'}));T.forEach((t,i)=>{el(s,'path',{d:'M'+B.map((_,j)=>`${col(j)} ${row(i)+dy(j)}`).join(' L '),fill:'none',stroke:GRID,'stroke-width':1,class:'draw',pathLength:1});label(s,195,row(i)+3,t,{'text-anchor':'end'});B.forEach((b,j)=>{const a=DATA.town_matrix.find(a=>a.town===t&&a.band===b);if(!a)return;const r=Math.sqrt(a.v/max)*16,c=el(s,'circle',{cx:col(j),cy:row(i)+dy(j),r,fill:a.v>=8000?INK:a.v>=6000?L[2]:L[4],class:'pop',style:`animation-delay:${i*.08+j*.02}s`});tip(c,`${t} · ${b} years: median ${money(a.v)}/m²; n=${a.n}`);label(s,col(j),row(i)+dy(j)+28,Math.round(a.v).toLocaleString(),{'font-size':9,'text-anchor':'middle'})})});label(s,70,390,'Area = median S$/m² · black ≥8k, medium 6–<8k, light <6k · blank = no sales',{fill:L[2]})}
// F8 Plumb Scatter: actual town summaries, barcode floor and plumb lines.
function scatter(s){const D=DATA.towns,X0=80,X1=795,base=285,minX=40,maxX=100,maxY=12000,x=v=>X0+(v-minX)/(maxX-minX)*(X1-X0),yy=v=>base-v/maxY*235;for(let k=0;k<=30;k++)el(s,'line',{x1:X0+k/30*(X1-X0),x2:X0+k/30*(X1-X0),y1:base,y2:base-(k%5?4:8),stroke:GRID,'stroke-width':.6});[40,60,80,100].forEach(v=>label(s,x(v),308,v,{'text-anchor':'middle'}));[0,4000,8000,12000].forEach(v=>{label(s,65,yy(v)+3,money(v),{'font-size':9,'text-anchor':'end'});el(s,'line',{x1:X0,x2:X1,y1:yy(v),y2:yy(v),stroke:GRID,'stroke-width':.5})});const sorted=[...D].sort((a,b)=>b.psm-a.psm),heroes=[sorted[0],sorted.at(-1)];D.forEach((a,i)=>{el(s,'line',{x1:x(a.lease),x2:x(a.lease),y1:base,y2:yy(a.psm),stroke:L[4],'stroke-width':.55});const c=el(s,'circle',{cx:x(a.lease),cy:yy(a.psm),r:heroes.includes(a)?4.5:3,fill:INK,class:'pop',style:`animation-delay:${i*.03}s`});tip(c,`${a.name}: median lease ${a.lease.toFixed(2)} years; median ${money(a.psm)}/m²; n=${a.n}`);if(heroes.includes(a))label(s,x(a.lease),yy(a.psm)-12,a.name,{'font-size':10,'text-anchor':'middle'})});label(s,80,345,'Horizontal = median remaining lease (years) · vertical = median S$/m²',{fill:L[2]});label(s,80,370,'One dot = one of the 20 towns with most 2025 transactions · hover for full values',{fill:L[2]})}
// G3 Chunky Bars: Chart.js capsule tops, 900ms quartic entry and value labels.
function chunky(node){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;Chart.getChart(node)?.destroy();new Chart(node,{type:'bar',data:{labels:DATA.lease.map(a=>a.name),datasets:[{data:DATA.lease.map(a=>a.v),backgroundColor:DATA.lease.map(a=>a.v===Math.max(...DATA.lease.map(b=>b.v))?INK:L[3]),borderRadius:{topLeft:99,topRight:99},borderSkipped:false,barPercentage:.52}]},options:{maintainAspectRatio:false,animation:reduced?false:{duration:900,easing:'easeOutQuart',delay:c=>c.type==='data'?c.dataIndex*110:0},layout:{padding:{top:35}},plugins:{legend:{display:false},tooltip:{callbacks:{label:i=>`${money(i.raw)}/m²; n=${DATA.lease[i.dataIndex].n}`}}},scales:{x:{grid:{display:false},border:{display:false},ticks:{font:{size:12,weight:600},color:INK}},y:{beginAtZero:true,max:9000,ticks:{callback:v=>money(v),color:L[2]},grid:{color:GRID},border:{display:false}}}},plugins:[{id:'topValues',afterDatasetsDraw(c){c.getDatasetMeta(0).data.forEach((bar,i)=>{c.ctx.save();c.ctx.font='800 14px Inter,Arial';c.ctx.fillStyle=INK;c.ctx.textAlign='center';c.ctx.fillText(money(c.data.datasets[0].data[i]),bar.x,bar.y-10);c.ctx.restore()})}}]})}
// G10 Diverging Bar: signed values, zero markLine and rounded outer bar ends.
function gaps(node){const g=echarts.getInstanceByDom(node)||echarts.init(node,null,{renderer:'svg'});g.clear();g.setOption({textStyle:{fontFamily:'Inter,Arial,sans-serif'},animation:!matchMedia('(prefers-reduced-motion: reduce)').matches,animationDuration:900,animationEasing:'quarticOut',animationDelay:i=>i*80,tooltip:{...MONO.tipLight,formatter:p=>{const a=DATA.gaps[p.dataIndex];return `${a.name}<br>Under 60: ${money(a.a)}/m² (n=${a.na})<br>80–99: ${money(a.b)}/m² (n=${a.nb})<br>Difference: ${a.v.toFixed(1)}%`}},grid:{left:150,right:70,top:20,bottom:40},xAxis:{type:'value',min:-60,max:0,splitLine:{lineStyle:{color:GRID}},axisLabel:{formatter:v=>v+'%',color:L[2]},axisLine:{show:false},axisTick:{show:false}},yAxis:{type:'category',data:DATA.gaps.map(a=>a.name),inverse:true,axisLine:{show:false},axisTick:{show:false},axisLabel:{color:L[2],fontFamily:'Inter,Arial,sans-serif',fontSize:12,fontWeight:600}},series:[{type:'bar',barWidth:23,data:DATA.gaps.map(a=>({name:a.name,value:a.v,itemStyle:{color:a.v>0?INK:L[3],borderRadius:a.v>0?[0,12,12,0]:[12,0,0,12]}})),label:{show:true,position:'left',formatter:p=>p.value.toFixed(1)+'%',fontWeight:800,color:INK,fontSize:12},markLine:{symbol:'none',silent:true,label:{show:false},lineStyle:{color:MUTED,width:1.5},data:[{xAxis:0}]}}]});window.addEventListener('resize',()=>g.resize())}
// G4 Dot Waffle: 10×10 circles. Final percentage-point dot split without invented records.
function waffle(s){const M=DATA.million,p=M.pct,COLS=10,CELL=25,R=8,X0=90,Y0=35;for(let i=0;i<100;i++){const x=X0+i%10*CELL,y=Y0+Math.floor(i/10)*CELL;const c=el(s,'circle',{cx:x,cy:y,r:R,fill:L[5],class:'pop',style:`animation-delay:${i*.008}s`});tip(c,'One percentage point of 2025 transactions, not one home');if(i+1<=p)el(s,'circle',{cx:x,cy:y,r:R,fill:INK,class:'pop',style:`animation-delay:${i*.008}s`});else if(i<p){const fraction=p-i;const a=-Math.PI/2,b=a+2*Math.PI*fraction;el(s,'path',{d:`M${x} ${y} L${x+R*Math.cos(a)} ${y+R*Math.sin(a)} A${R} ${R} 0 ${fraction>.5?1:0} 1 ${x+R*Math.cos(b)} ${y+R*Math.sin(b)} Z`,fill:INK})}}label(s,400,100,M.pct.toFixed(2)+'%',{'font-size':48,'font-weight':800});label(s,400,137,'sold for S$1 million or more',{'font-size':18});label(s,400,175,`${M.n.toLocaleString()} of ${M.total.toLocaleString()} sales`,{'font-size':16});label(s,400,216,`${M.short_n} million-dollar sales had <60 years left`,{'font-size':14});label(s,90,325,'Black = ≥S$1m · light = below S$1m · one dot = one percentage point',{fill:L[2]});label(s,90,350,'The partly filled dot preserves the exact proportion; it is not an individual transaction.',{fill:L[2],'font-size':10})}
'''
css="body{max-width:1080px;margin:auto}.grid2{display:block}svg{width:100%;height:auto;display:block}.card{margin-bottom:26px}h1{font-size:32px;letter-spacing:-.04em;margin:28px}.sub{color:#6A6963;line-height:1.6}.note{font-size:13px;line-height:1.7;color:#4A4944;margin:18px 0}.src{color:#6A6963}nav{margin:28px;line-height:2}a{color:inherit}.wrap,.ch{height:390px}button{font:inherit;color:#1C1C1A;background:#F0EFEB;border:1px solid #8F8E88;border-radius:12px;padding:8px;margin:10px 0}@media(max-width:600px){body{padding:8px}h1{font-size:24px}.card{padding:14px}.wrap,.ch{height:340px}}"
notice='<!-- Lieflat-derived software: https://polyformproject.org/licenses/noncommercial/1.0.0 -->'
head='<!doctype html>'+notice+'<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HDB prices — three chart styles</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>'+css+'</style></head><body>'
common='<script>'+tokens+'\ndocument.head.prepend(Object.assign(document.createElement("style"),{textContent:MONO.CARD_CSS}));const DATA='+json.dumps(DATA)+';'+base+new+'</script>'
specs=[
('editorial','01-market-rhythm','Monthly prices show the market context for lease ageing','L3 Barcode Lollipop','barcode','2025 · S$/m² monthly median · one mark = one registration month','Monthly summaries include every 2025 transaction. These are nominal market prices, not a depreciation curve. Transaction composition can change month to month.',360),
('editorial','02-town-lease','The lease-price relationship differs across towns','L4 Arc Matrix','arcs','2025 · six high-volume towns with sufficient short- and long-lease sales · area = median S$/m²','All flat types are included. Cell sample sizes are available on hover; small cells are less stable. Comparing the same town reduces one source of confounding but does not control flat type, model, size, storey, or estate micro-location.',420),
('editorial','03-lease-mix','The mix of remaining leases changes through time','L9 Bubble Almanac','almanac','2017–2026 · bubble area = transaction count · dashed = partial 2026','All 242,259 records are counted once. 2026 is partial through October; the upload extraction date is unknown. Volume comparisons with complete years need care.',500),
('basics','01-lease-value','The longest leases have the highest overall median price per m²','F5 Tick Rows','rows','2025 · lease bands in years · median S$/m² · one tick = S$100/m²','Below 80 years, the pooled medians are not monotonic. These medians are unadjusted and should not be used as a fixed depreciation schedule.',360),
('basics','02-town-scatter','Town-level lease length alone cannot explain price differences','F8 Plumb Scatter','scatter','2025 · 20 highest-volume towns · one dot = a town summary','Horizontal position is median remaining lease; vertical position is median sale price per square metre. These are separate medians, not the characteristics of one typical home. No town-level correlation is interpreted as a causal effect.',400),
('basics','03-type-growth','Common flat types sold for more in 2025 than in 2017','F6 Paired Rungs','pairs','2017 versus 2025 · median nominal resale price · light/black series','Different homes are sold in each year; this is not a repeat-sale analysis. Rare 1-room and multi-generation types remain in the source data and all-record charts.',360),
('glance','01-lease-value','80–99-year leases stand out in the pooled price comparison','G3 Chunky Bars','chunky','2025 · lease bands in years · bar height = median S$/m²','Bars start at zero. Median price per square metre is calculated per sale before taking the median. Size normalization does not remove differences in location and flat type.',0),
('glance','02-town-gap','Shorter-lease sales have lower medians within these towns','G10 Diverging Bar','gaps','2025 · <60 versus 80–99 years · signed percentage difference in median S$/m²','Difference = (short-lease median ÷ long-lease median − 1) × 100. Selected towns are the six highest-volume among those with at least 30 transactions in each comparison band. This is an association, not an annual depreciation rate.',0),
('glance','03-million-dollar',f"Only {DATA['million']['pct']:.2f}% of 2025 sales reached S$1 million",'G4 Dot Waffle','waffle','2025 · one dot = one percentage point · fractional dot = exact remainder','Million-dollar sales are a small share of this file’s transactions. Some have fewer than 60 lease years remaining, so short leases do not rule out high absolute prices. Prices at exactly S$1m are included; no inflation adjustment.',380)]
groups={k:[] for k in ['editorial','basics','glance']};checks=[]
for family,name,title,template,fn,sub,note,height in specs:
 folder=OUT/family;folder.mkdir(exist_ok=True)
 if fn=='chunky':container='<div class="wrap"><canvas id="chart" role="img" aria-label="'+title+'"></canvas></div>';dependency='chart.umd.min.js'
 elif fn=='gaps':container='<div class="ch" id="chart" role="img" aria-label="'+title+'"></div>';dependency='echarts.min.js'
 else:container=f'<svg id="chart" viewBox="0 0 880 {height}" role="img" aria-label="{title}"></svg>';dependency=None
 card=f'<article class="card"><h2>{title}</h2><div class="sub">{sub}</div>{container}<p class="note">{note}</p><div class="src">{template} · {family.upper()} · USER-SUPPLIED HDB RESALE CSV</div><button id="replay">Replay chart</button></article>'
 lib=''
 if dependency:lib='<script>'+(OUT/'vendor'/dependency).read_text().replace('</script>','<\\/script>')+'</script>'
 activation=f"<script>obsReveal('chart',{fn});document.getElementById('replay').onclick=()=>document.getElementById('chart').dispatchEvent(new Event('click'));</script>"
 page=head+f'<nav><a href="../index.html">All three styles</a> · <a href="../transactions.csv" download>Original CSV</a></nav>'+card+lib+common+activation+'</body></html>'
 (folder/(name+'.html')).write_text(page);groups[family].append(dict(name=name,title=title,template=template));checks.append(dict(family=family,file=name+'.html',fn=fn))
index=head+'<h1>One HDB dataset, three visual languages</h1><p class="note" style="margin:28px">242,259 transactions · January 2017–October 2026 · English charts. Select a style below. Charts summarize observed sales, not causal depreciation. 2025 is the latest complete calendar year in this file; 2026 is partial.</p><nav><a href="transactions.csv" download>Original CSV</a> · <a href="methodology.md">Methods and template audit</a> · <a href="../hdb/index.html">Complete searchable transaction ledger</a></nav>'
for family,items in groups.items():
 name={'editorial':'Lupi Editorial — slow-reading data stories','basics':'Lupi Basics — familiar forms, fine detail','glance':'Glance — quick comparisons'}[family]
 index+='<article class="card"><h2>'+name+'</h2><p class="note">'+(' · '.join(a['template'] for a in items))+'</p>'
 for a in items:index+=f'<p class="note"><a href="{family}/{a["name"]}.html">{a["title"]}</a> · <a href="{family}/{a["name"]}.png">PNG</a></p>'
 index+='</article>'
index+=common+'</body></html>';(OUT/'index.html').write_text(index);(OUT/'manifest.json').write_text(json.dumps(checks,indent=2))
shutil.copyfile(SKILL/'LICENSE',OUT/'LIEFLAT-LICENSE.md')
print(json.dumps({'records':len(d),'year_2025':len(y),'million':DATA['million'],'selected_town_gaps':DATA['gaps']},indent=2))
