from pathlib import Path
import pandas as pd,numpy as np,json,shutil,gzip,base64,hashlib
root=Path(__file__).resolve().parents[2]; out=root/'charts/hdb'; skill=root/'.codex/skills/lieflat-charts'; src=out/'transactions.csv'
# Original transactions.csv is retained as the regeneration source.
d=pd.read_csv(src);d['year']=d.month.str[:4].astype(int);d['lease']=d.remaining_lease.str.extract(r'(\d+) years')[0].astype(int)+d.remaining_lease.str.extract(r'(\d+) months')[0].fillna(0).astype(int)/12;d['psm']=d.resale_price/d.floor_area_sqm
bins=[0,50,60,70,80,100]; labels=['Under 50','50–<60','60–<70','70–<80','80–99'];d['band']=pd.cut(d.lease,bins,right=False,labels=labels)
latest=d[d.year==2025]
annual=[dict(name=str(y),v=float(g.resale_price.median()),n=len(g)) for y,g in d.groupby('year')]
lease=[dict(name=str(b),v=float(g.psm.median()),n=len(g)) for b,g in latest.groupby('band',observed=True)]
box=[]
for b,g in latest.groupby('band',observed=True):
 v=g.psm; q1,md,q3=v.quantile([.25,.5,.75]); inside=v[(v>=q1-1.5*(q3-q1))&(v<=q3+1.5*(q3-q1))]; outs=v[~v.index.isin(inside.index)]
 box.append(dict(name=str(b),q=[float(inside.min()),float(q1),float(md),float(q3),float(inside.max())],outs=list(map(float,outs)),n=len(g)))
types=['2 ROOM','3 ROOM','4 ROOM','5 ROOM','EXECUTIVE'];paired=[]
for t in types:
 g=d[d.flat_type==t];a=g[g.year==2017];b=g[g.year==2025];paired.append(dict(name=t.replace(' ROOM','-room').title(),a=float(a.resale_price.median()),b=float(b.resale_price.median()),na=len(a),nb=len(b)))
matrix=[dict(year=int(y),band=str(b),n=len(g)) for (y,b),g in d.groupby(['year','band'],observed=True)]
data=dict(annual=annual,lease=lease,box=box,paired=paired,matrix=matrix,bands=labels,total=len(d))
(out/'chart-data.json').write_text(json.dumps(data,indent=2))
tokens=(skill/'mono-tokens.js').read_text().replace('</script>', '<\\/script>')
render=r'''
const {el,txt,tip,obsReveal,rnd,blob,INK,PAPER,MUTED,GRID,L}=MONO;
const money=v=>'S$'+Math.round(v).toLocaleString('en-SG');
const label=(s,x,y,text,more={})=>txt(s,{x,y,fill:INK,'font-size':10,'font-weight':600,...more},text);
function grid(s,max,base=270,top=35){const map=v=>base-v/max*(base-top);for(let i=0;i<=4;i++){const v=max*i/4;el(s,'line',{x1:70,x2:820,y1:map(v),y2:map(v),stroke:GRID,'stroke-width':.6});label(s,62,map(v)+3,money(v),{'text-anchor':'end','font-size':9,fill:L[2]})}return map}
// F2 · Hairline Line: calendar floor, hairline path, period dots and separated labels.
function line(s){const D=DATA.annual,base=270,map=grid(s,800000),x=i=>90+i*78;D.forEach((a,i)=>el(s,'line',{x1:x(i),x2:x(i),y1:base,y2:base-8,stroke:GRID,'stroke-width':.6}));el(s,'path',{d:'M'+D.map((a,i)=>`${x(i)} ${map(a.v)}`).join(' L '),fill:'none',stroke:INK,'stroke-width':1,pathLength:1,class:'draw'});D.forEach((a,i)=>{const dot=el(s,'circle',{cx:x(i),cy:map(a.v),r:3,fill:a.name==='2026'?PAPER:INK,stroke:INK,'stroke-width':1,class:'pop',style:`animation-delay:${i*.03}s`});tip(dot,`${a.name}: ${money(a.v)} median; ${a.n.toLocaleString()} records`);label(s,x(i),map(a.v)-13,money(a.v),{'text-anchor':'middle','font-size':9,'font-weight':800});label(s,x(i),290,a.name,{'text-anchor':'middle'})});label(s,70,330,'2026 is partial through October; hollow dot = incomplete year.',{fill:L[2]})}
// F5 · Tick Rows: one row per lease band, tick units and every-fifth markers.
function rows(s){const D=DATA.lease,X0=145,PX=8,unit=100,y0=i=>45+i*55;D.forEach((a,i)=>{const y=y0(i);label(s,130,y+4,a.name,{'text-anchor':'end'});el(s,'line',{x1:X0,x2:800,y1:y+9,y2:y+9,stroke:GRID,'stroke-width':.6});for(let k=0;k<a.v/unit;k++){const x=X0+k*PX+PX/2,h=10+rnd(k+1,i+2)*6,frac=Math.min(1,a.v/unit-k);el(s,'line',{x1:x,x2:x,y1:y+9,y2:y+9-h*frac,stroke:INK,'stroke-width':.9,class:'fade',style:`animation-delay:${i*.08+k*.008}s`});if(k%5===4)el(s,'circle',{cx:x,cy:y+13,r:.8,fill:L[4]})}const lab=label(s,X0+a.v/unit*PX+12,y+4,money(a.v),{'font-weight':800});tip(lab,`${a.name} years remaining; n=${a.n}; median ${money(a.v)}/m²`)});label(s,145,330,'One full tick = S$100/m² · fractional last tick · dots mark S$500',{fill:L[2]})}
// F15 · Tick Box: whiskers, rounded IQR boxes, paper median and every outlier.
function boxes(s){const D=DATA.box,max=Math.ceil(Math.max(...D.flatMap(a=>[a.q[4],...a.outs]))/4000)*4000,map=grid(s,max),x=i=>145+i*145,BW=38;D.forEach((a,i)=>{const [mn,q1,md,q3,mx]=a.q,c=x(i);el(s,'line',{x1:c,x2:c,y1:map(mn),y2:map(mx),stroke:MUTED,'stroke-width':.8,class:'draw',pathLength:1});[mn,mx].forEach(v=>el(s,'line',{x1:c-10,x2:c+10,y1:map(v),y2:map(v),stroke:MUTED,'stroke-width':1}));const b=el(s,'rect',{x:c-BW/2,y:map(q3),width:BW,height:map(q1)-map(q3),rx:9,fill:L[1],class:'pop'});tip(b,`${a.name}; n=${a.n}; Q1=${money(q1)}, median=${money(md)}, Q3=${money(q3)}; whiskers=${money(mn)}–${money(mx)}; ${a.outs.length} outliers`);el(s,'line',{x1:c-BW/2+3,x2:c+BW/2-3,y1:map(md),y2:map(md),stroke:PAPER,'stroke-width':2.2});a.outs.forEach((v,k)=>{const o=el(s,'circle',{cx:c+(rnd(k+1,i+3)-.5)*12,cy:map(v),r:1.5,fill:PAPER,stroke:L[2],'stroke-width':.7});tip(o,`${a.name}: ${money(v)}/m²; outlier ${k+1}`)});label(s,c,290,a.name,{'text-anchor':'middle'});label(s,c,310,'n='+a.n.toLocaleString(),{'text-anchor':'middle','font-size':9,fill:L[2]})});label(s,70,340,'Box = middle 50% · paper tick = median · hollow = every 1.5×IQR outlier',{fill:L[2]})}
// F6 · Paired Rungs: two ladders per flat type, common zero baseline and units.
function pairs(s){const D=DATA.paired,base=270,unit=25000,max=1100000,map=grid(s,max),step=(base-35)/(max/unit);D.forEach((a,i)=>{const c=150+i*145;['a','b'].forEach((key,j)=>{const x=c+(j?17:-17),v=a[key];for(let k=0;k<v/unit;k++){const y=base-(k+.5)*step,frac=Math.min(1,v/unit-k),w=(12-1+rnd(k+1,i+2)*2)*frac;el(s,'line',{x1:x-w,x2:x+w,y1:y,y2:y,stroke:j?INK:L[4],'stroke-width':1,class:'fade',style:`animation-delay:${i*.08+k*.01}s`})}const t=label(s,x,map(v)-10,Math.round(v/1000)+'k',{'text-anchor':'middle','font-size':9,'font-weight':800,fill:j?INK:L[2]});tip(t,`${a.name}: ${key==='a'?'2017':'2025'} median ${money(v)}; n=${key==='a'?a.na:a.nb}`)});label(s,c,295,a.name,{'text-anchor':'middle'})});label(s,70,330,'Light = 2017 · black = 2025 · one full rung = S$25,000 · final rung fractional',{fill:L[2]})}
// L9 · Bubble Almanac: ledger hairlines, year rows, seeded blobs and marginal notes.
function almanac(s){const rowY=i=>65+i*37,colX=j=>155+j*125,max=Math.max(...DATA.matrix.map(a=>a.n));for(let y=43;y<=410;y+=7)el(s,'line',{x1:70,x2:800,y1:y,y2:y,stroke:GRID,'stroke-width':.5});DATA.bands.forEach((b,j)=>label(s,colX(j),28,b,{'text-anchor':'middle'}));for(let i=0;i<10;i++){el(s,'line',{x1:70,x2:800,y1:rowY(i),y2:rowY(i),stroke:L[5],'stroke-width':.7});label(s,62,rowY(i)+3,String(2017+i),{'text-anchor':'end'})}DATA.matrix.slice().sort((a,b)=>b.n-a.n).forEach((a,k)=>{const i=a.year-2017,j=DATA.bands.indexOf(a.band),x=colX(j),y=rowY(i),r=Math.sqrt(a.n/max)*18;const p=el(s,'path',{d:blob(x,y,r,i*5+j),fill:a.year===2026?PAPER:L[4],stroke:INK,'stroke-width':.6,'stroke-dasharray':a.year===2026?'3 3':'none',class:'pop',style:`animation-delay:${k*.012}s`});tip(p,`${a.year} · ${a.band} years: ${a.n.toLocaleString()} transactions`);label(s,x+28,y+3,a.n.toLocaleString(),{'font-size':9,fill:L[2]})});label(s,70,446,'Area ∝ transaction count · dashed = partial 2026 · no transaction is removed',{fill:L[2]});el(s,'path',{d:'M760 398 L785 428',fill:'none',stroke:MUTED,'stroke-width':.7});label(s,70,474,'Side note: transaction mix changes over time; these are not repeat sales of identified flats.',{fill:L[2],'font-size':10})}
'''
meta=[('01-market-context','Prices rose while leases continued to run down','Annual median resale price · S$ nominal · one dot = one year · 2017–2026', 'F2 Hairline Line','line','Annual medians are transaction summaries, not an HDB price index. Changes in the homes sold affect this line. No inflation adjustment is applied.'),('02-lease-price','The longest-lease band commands a higher median per square metre','2025 · remaining lease in years · S$/m² · each band includes every matching sale','F5 Tick Rows','rows','The relationship is not monotonic below 80 years. This cross-sectional comparison does not isolate lease depreciation; town, model, storey and flat type are not controlled.'),('03-price-overlap','Lease bands contain widely overlapping prices','2025 · S$/m² · five-number distribution by remaining lease · hover for details','F15 Tick Box','boxes','Whiskers extend to the furthest observed values within 1.5×IQR. All outliers are plotted; overlapping marks may coincide. No trimming or winsorisation is used.'),('04-type-comparison','Common flat types sold for more in 2025 than in 2017','Median nominal resale price · S$ · common flat types · matched calendar years, not matched homes','F6 Paired Rungs','pairs','These are different transactions in each year, not the same properties resold. The rare 1-room and multi-generation categories remain in the full ledger and other all-record charts; they are omitted only from this common-type comparison.'),('05-transaction-mix','The lease mix behind market prices changes each year','2017–2026 · bubble area = transaction count · columns = remaining-lease bands','L9 Bubble Almanac','almanac','All 242,259 records are counted exactly once here. The under-50-year band includes observed leases from 39 years 4 months. The final band has an exclusive upper bound of 100 years.')]
css="body{max-width:1060px;margin:auto}svg{width:100%;height:auto;display:block}h1{font-size:32px;letter-spacing:-.04em;margin:20px 28px}p.note{font-size:13px;line-height:1.65;color:#4A4944;margin-top:22px}.src{color:#6A6963}a{color:inherit}.sub{color:#6A6963;line-height:1.6}nav{margin:28px;line-height:2}button,input,select{font:inherit;padding:8px;background:#F0EFEB;color:#1C1C1A;border:1px solid #8F8E88;border-radius:8px}table{border-collapse:collapse;font-size:11px}td,th{padding:8px;text-align:left;border-bottom:1px solid #DEDDD6}.ledger{margin:28px;overflow:auto}.card{margin-bottom:30px}@media(max-width:600px){body{padding:12px}h1{font-size:25px}.card{padding:16px}}"
head='<!doctype html><!-- Template-derived software: Lieflat Charts, https://polyformproject.org/licenses/noncommercial/1.0.0 --><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HDB: lease and resale prices</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>'
# CSS evaluated from exact token template via Node separately below; inline identical token CSS runtime injection.
script='<script>'+tokens+'\ndocument.head.prepend(Object.assign(document.createElement("style"),{textContent:MONO.CARD_CSS}));\nconst DATA='+json.dumps(data)+';\n'+render
cards=[]
for name,title,sub,template,fn,note in meta:
 height=500 if fn=='almanac' else 360
 card=f'<article class="card"><h2>{title}</h2><div class="sub">{sub}</div><svg id="{fn}" viewBox="0 0 880 {height}" role="img" aria-label="{title}"></svg><p class="note">{note}</p><div class="src">{template} · LUPI / MONO · USER-SUPPLIED HDB RESALE CSV</div></article>'
 cards.append(card)
 (out/(name+'.html')).write_text(head+css+'</style><body>'+card+script+f"obsReveal('{fn}',{fn});</script></body></html>")
compressed=base64.b64encode(gzip.compress(src.read_bytes())).decode()
ledger=r'''
let records=[],selected=[],page=0;const size=50;
function parseCSV(text){const result=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if(c==='\n'&&!quote){row.push(cell.replace(/\r$/,''));result.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);result.push(row)}return result}
const enc=PAYLOAD;document.getElementById('load').onclick=async()=>{const bytes=Uint8Array.from(atob(enc),c=>c.charCodeAt(0));const text=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();const parsed=parseCSV(text);window.cols=parsed.shift();records=parsed;selected=records.map((r,i)=>i);document.getElementById('load').hidden=true;show()};
function show(){const box=document.getElementById('table');box.replaceChildren();const table=document.createElement('table');const header=document.createElement('tr');['Record ID',...cols].forEach(v=>{const th=document.createElement('th');th.textContent=v;header.append(th)});table.append(header);selected.slice(page*size,(page+1)*size).forEach(i=>{const tr=document.createElement('tr');[i+1,...records[i]].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});table.append(tr)});box.append(table);document.getElementById('status').textContent=`${selected.length.toLocaleString()} records · page ${page+1} of ${Math.max(1,Math.ceil(selected.length/size))}`}
document.getElementById('query').oninput=e=>{if(!records.length)return;const q=e.target.value.toLowerCase();selected=records.flatMap((r,i)=>r.join(' ').toLowerCase().includes(q)?[i]:[]);page=0;show()};document.getElementById('prev').onclick=()=>{if(page>0){page--;show()}};document.getElementById('next').onclick=()=>{if((page+1)*size<selected.length){page++;show()}};
'''
intro='<h1>The lease clock and the resale market</h1><p class="note" style="margin:28px">Five charts for an article on HDB depreciation. 242,259 supplied transactions, January 2017–October 2026. A lease has less time remaining as it ages; observed market prices need not fall with it. These charts describe transactions and do not estimate a causal depreciation curve. October 2026 and the final year may be incomplete; the file’s extraction date is unknown.</p>'
nav='<nav><a href="transactions.csv" download>Download every original record (CSV)</a> · <a href="methodology.md">Methods & template selection</a></nav>'
controls='<section class="ledger"><h2>Every transaction, retained</h2><p class="note">Original row order, original field text, including duplicate rows. Record ID is the 1-based data-row position, not a property identifier. Search any field; 50 records per page. The full CSV is also embedded here for offline access.</p><button id="load">Open all 242,259 records</button> <input id="query" aria-label="Search all records" placeholder="Search town, month, block…"><button id="prev">Previous</button><button id="next">Next</button><p id="status" class="note"></p><div id="table"></div></section>'
(out/'index.html').write_text(head+css+'</style><body>'+intro+nav+''.join(cards)+controls+script+'\n'+''.join(f"obsReveal('{fn}',{fn});" for *_,fn,note in meta)+'\nconst PAYLOAD="'+compressed+'";\n'+ledger+'</script></body></html>')
sha=hashlib.sha256(src.read_bytes()).hexdigest()
(out/'methodology.md').write_text(f'''# HDB lease and resale charts — methodology

Source: user-supplied “{src.name}”; not independently reconciled with a live official dataset. {len(d):,} records, 11 original columns, no blank fields. Date range 2017-01–2026-10. CSV SHA-256: {sha}. transactions.csv is byte-identical to the upload. No deduplication, synthetic observations, trimming, or replacement of values. All records remain searchable in index.html, including rare flat types.

Remaining lease = stated years + stated months / 12; absent month component means zero months. S$/m² = resale_price / floor_area_sqm for each sale, then median; not ratio of aggregate medians. Bands are [0,50), [50,60), [60,70), [70,80), [80,100). Medians and quartiles use pandas linear quantile interpolation. F15 uses Tukey 1.5×IQR whiskers and plots every outlier. Distinct transactions may have coincident marks. All statistics are nominal SGD. Annual data are not repeat-sale observations or inflation-adjusted index values.

## Candidate audit and template provenance

The full catalog was evaluated first for Lupi Editorial, then Basics. L1 birth/current-scale fan, L6 network, L7 bipolar scales, L10 time-of-day, L11 event life histories, L13 funnel, L14 composition and L15 ballot percentages do not match price/lease data. L5/L12 record lists cannot legibly hold 242,259 items; L2's unit cascade does not encode continuous transaction prices. L3 is a short daily barcode, not suitable for nearly ten years of monthly transactions. L4 fits a small matrix, but L9 offers year rows and editorial marginalia for the lease mix. L8 decorative grids add no explanatory dimension. No Glance fallback is needed.

1. **F2 Hairline Line**, basics-gallery.html, “Thirty days of sign-ups”: calendar floor, thin polyline and period dots preserved; ten annual rather than daily summaries. Compared L3 (too many periods if using monthly data), F3 (area would overemphasize accumulated volume), F2 (explicit period medians). Annual aggregation is stated, not disguised as individual transactions.
2. **F5 Tick Rows**, basics-gallery.html, “Six teams, shipped and counted”: horizontal tick queues, guide lines, every-fifth dots. Compared L2 (vertical names and integer-unit composition less suitable), F1 (labels and exact median annotations more crowded), F5 (horizontal lease labels fit). One tick is S$100/m²; final tick is fractional, no rounding of the encoded median.
3. **F15 Tick Box**, basics-gallery.html, “Reply times, boxed by plan”: rounded IQR boxes, hairline whiskers, paper median, hollow outliers. Direct five-number-summary exception applies. F8 scatter is capped at 20 entities; F5 medians omit overlap; L19 density needs smoothing assumptions and is a reserve template. This is a statistical summary, not one point per input row.
4. **F6 Paired Rungs**, basics-gallery.html, “This year against last, plan by plan”: paired ladders, light/black series and zero baseline. Compared F12 (good for a few before/after endpoints but less natural for monetary rung units), F2 (would duplicate the temporal overview), F6 (distinct price/type comparison). One rung = S$25,000, final rung fractional. The common-type chart alone excludes rare 1-room and multi-generation groups; no raw records are removed.
5. **L9 Bubble Almanac**, lupi-gallery.html, “Eight years of tickets, one almanac”: ledger paper, year rows, seeded blob marks, side notes; radius proportional to square root of count, with fixed maximum radius. Compared L4 (little room for year context), F10 (week/hour contract wrong), L9 (year/category matrix matches). Original beta outline becomes a clearly labelled partial-year outline. Decorative randomness never alters values or positions.

All chart structures derive from these actual gallery rendering blocks. Dimensions and labels are adapted for English article inserts. MONO tokens are inlined; monochrome was chosen because a shared extra color dimension would add no stable information. Charts work offline with a system sans-serif fallback; Inter loads when network is available. Hover shows exact summary counts; chart clicks replay reveal. Reduced-motion CSS is included. The ledger loads on demand to avoid 242,259 DOM rows. It retains each original row and supports search/pagination. Five individual HTML charts accompany the combined chart page.

## Article interpretation

Market appreciation can coexist with lease ageing. Long-lease sales have higher unadjusted median S$/m² in 2025, but below 80 years the medians are not monotonic. Large within-band spread makes a single depreciation percentage misleading. Estimates of causal lease effects would require a separate controlled model and stronger identification; no such rate is inferred here. Remaining lease is measured at transaction time. Registration month is not necessarily contract date. No unique flat ID is supplied, so repeat-sale tracking is not assumed.
''')
print(json.dumps({'records':len(d),'matrix_total':sum(a['n'] for a in matrix),'csv_sha256':sha,'box_counts':sum(a['n'] for a in box),'2025_total':len(latest)},indent=2))
